language: cpp
sudo: required
compiler: clang
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_install:
- echo "hiNick"
- brew update && brew install cmake
script:
- cmake -H. -Bbuild
- cmake --build build
- ./bin/point_test
- echo "Done!"
